// auth
export const EMAIL_CHANGED = 'EMAIL_CHANGED'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED'

//employee
export const EMPLOYEE_CREATE = 'EMPLOYEE_CREATE'
export const EMPLOYEE_SAVE_SUCCESS = 'EMPLOYEE_SAVE_SUCCESS'
export const EMPLOYEE_SET = 'EMPLOYEE_SET'
export const EMPLOYEE_UPDATE = 'EMPLOYEE_UPDATE'
export const EMPLOYEES_FETCH_SUCCESS = 'EMPLOYEES_FETCH_SUCCESS'